### ISSUE TITLE
Issue compiling in Ubuntu 14.04

### ISSUE THREAD

**Issue by ounelly70** [nmav/ipcalc#1]
It's likely me just being a novice, but I'm having issues compiling this in Ubuntu

ounelly70@ubuntu1:~/downloads/ipcalc-master$ make
cc -O2 -g -Wall -DUSE_GEOIP -DUSE_DYN_GEOIP -DLIBPATH="\"/usr/lib64\"" -DVERSION="\"0.1.7\"" ipcalc.c ipcalc-geoip.c -o ipcalc  -ldl
ipcalc-geoip.c: In function ‘geo_ipv4_lookup’:
ipcalc-geoip.c:135:64: error: ‘GEOIP_SILENCE’ undeclared (first use in this function)
  gi = pGeoIP_open_type(GEOIP_COUNTRY_EDITION, GEOIP_STANDARD | GEOIP_SILENCE);
                                                                ^
ipcalc-geoip.c:135:64: note: each undeclared identifier is reported only once for each function it appears in
ipcalc-geoip.c: In function ‘geo_ipv6_lookup’:
ipcalc-geoip.c:199:67: error: ‘GEOIP_SILENCE’ undeclared (first use in this function)
  gi = pGeoIP_open_type(GEOIP_COUNTRY_EDITION_V6, GEOIP_STANDARD | GEOIP_SILENCE);
                                                                   ^
ipcalc-geoip.c: In function ‘geo_ipv4_lookup’:
ipcalc-geoip.c:164:12: warning: ignoring return value of ‘asprintf’, declared with attribute warn_unused_result [-Wunused-result]
    asprintf(coord, "%f,%f", gir->latitude, gir->longitude);
            ^
ipcalc-geoip.c:178:13: warning: ignoring return value of ‘asprintf’, declared with attribute warn_unused_result [-Wunused-result]
     asprintf(coord, "%f,%f", gir->latitude, gir->longitude);
             ^
ipcalc-geoip.c: In function ‘geo_ipv6_lookup’:
ipcalc-geoip.c:228:12: warning: ignoring return value of ‘asprintf’, declared with attribute warn_unused_result [-Wunused-result]
    asprintf(coord, "%f,%f", gir->latitude, gir->longitude);
            ^
ipcalc-geoip.c:242:13: warning: ignoring return value of ‘asprintf’, declared with attribute warn_unused_result [-Wunused-result]
     asprintf(coord, "%f,%f", gir->latitude, gir->longitude);
             ^
make: *** [ipcalc] Error 1

**Comment by nmav** [comment]
You need to have libgeoip-dev installed. If you already have it and it doesn't compile you should compile as "make USE_GEOIP=no"

**Comment by ounelly70** [comment]
Fantastic!  Thank you!

I did have libgeoip-dev installed, but the command you gave worked :)
