### ISSUE TITLE
--all-info doesn't show all info at all (Fedora 24)

### ISSUE THREAD

**Issue by q2dg** [nmav/ipcalc#5]
If I execute:
        ipcalc --all-info 192.168.3.0
I only get this output
       Address:	192.168.3.0
       Reverse DNS:	0.3.168.192.in-addr.arpa.
       Address space:	Private Use
       Address class:	Class C
instead of example output shown in Readme.md
Thanks

**Comment by nmav** [comment]
Because you provided an IP address instead of a network. Try:
```ipcalc --all-info 192.168.3.0/255.255.255.0```

**Comment by q2dg** [comment]
Yes, you're true!! 
Thanks (and sorry)
