### ISSUE TITLE
Won't compile on macOS 

### ISSUE THREAD

**Issue by ShiveringBear** [nmav/ipcalc#8]
I am trying to get this to work on MacOS, but I'm getting the warnings and error below.  I tried the ipecac on Homebrew, but it only supports IPv4.  I now need IPv6.  Unfortunately I am not a developer, or I would fix it myself, and upload the fix.  Please help!  

$ sudo make
cc -O2 -g -Wall -DUSE_GEOIP -DUSE_DYN_GEOIP -DLIBPATH="\"/usr/lib64\"" -DVERSION="\"0.2.0\"" ipcalc.c ipcalc-geoip.c ipcalc-reverse.c netsplit.c -o ipcalc  -ldl
ipcalc.c:497:12: warning: comparison of unsigned expression >= 0 is always true [-Wtautological-compare]
        if (byte1 >= 0 && byte1 < 128) {
            ~~~~~ ^  ~
ipcalc.c:521:12: warning: comparison of unsigned expression >= 0 is always true [-Wtautological-compare]
        if (byte1 >= 0 && byte1 < 128) {
            ~~~~~ ^  ~
ipcalc.c:1529:45: warning: address of array 'info.hosts' will always evaluate to 'true' [-Wpointer-bool-conversion]
                if ((flags & FLAG_SHOW_ADDRESSES) && info.hosts) {
                                                  ~~ ~~~~~^~~~~
3 warnings generated.
netsplit.c:215:12: error: no member named 's6_addr16' in 'struct in6_addr'
                        if (end.s6_addr16[k] != 0xffff)
                            ~~~ ^
1 error generated.
make: *** [ipcalc] Error 1

**Comment by nmav** [comment]
It seems that this structure member is non-standard. I've updated the code to use the standard value.

**Comment by ShiveringBear** [comment]
Thank you, it worked perfectly!
